### ISSUE TITLE
Error generating documentation

### ISSUE THREAD

**Issue by layssi** [lava-nc/lava-docs#7]
Traceback (most recent call last):
  File "~/lava/.pybuilder/plugins/cpython-3.8.11.final.0/lib/python3.8/site-packages/sphinx/cmd/build.py", line 276, in build_main
    app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
  File "~/lava/.pybuilder/plugins/cpython-3.8.11.final.0/lib/python3.8/site-packages/sphinx/application.py", line 216, in __init__
    self.config = Config.read(self.confdir, confoverrides or {}, self.tags)
  File "~/lava/.pybuilder/plugins/cpython-3.8.11.final.0/lib/python3.8/site-packages/sphinx/config.py", line 170, in read
    raise ConfigError(__("config directory doesn't contain a conf.py file (%s)") %
sphinx.errors.ConfigError: config directory doesn't contain a conf.py file (~/lava/docs)

Configuration error:
config directory doesn't contain a conf.py file (~/lava/docs)

**Comment by layssi** [comment]
Seems like Lava repositry didn't pull the docs
